### ISSUE TITLE
Can't compare offset-naive and offset-aware datetime

### ISSUE THREAD

**Issue by thomas-touhey** [jepler/leapseconddata#24]
While making examples for the documentation:

```
from datetime import datetime
from leapseconddata import LeapSecondData

my_date = datetime(2024, 7, 18, 22, 0, 0)
data = LeapSecondData.from_standard_source()

my_tai_date = data.to_tai(my_date)
print(my_tai_date.isoformat())
```

This yields the following error:

```
Traceback (most recent call last):
  File "/home/cake/Projets/misc/leapseconddata/docs/developer-guides/convert-utc-to-tai.py", line 7, in <module>
    my_tai_date = data.to_tai(my_date)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/cake/Projets/misc/leapseconddata/leapseconddata/__init__.py", line 205, in to_tai
    return (when + self.tai_offset(when, check_validity=check_validity)).replace(tzinfo=tai)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cake/Projets/misc/leapseconddata/leapseconddata/__init__.py", line 177, in tai_offset
    message = self._check_validity(when)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cake/Projets/misc/leapseconddata/leapseconddata/__init__.py", line 143, in _check_validity
    if when > self.valid_until:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
```

The expected behaviour is to consider the datetime the same as if UTC was set explicitely, as according to the docstring, "Moment in time to convert. If naive, it is assumed to be in UTC.". :)

**Comment by thomas-touhey** [comment]
Fixed by #29, AFAIK. Closing the issue. :)
